[package]
name = "thermite"
version = "0.1.0"
authors = ["Samuel","Patrick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.2.1"
